### ISSUE TITLE
Broken since vim 7.4 in Mac OS X Macericks

### ISSUE THREAD

**Issue by dciccale** [lepture/vim-css#5]
I am using MacVim 7.4 in Mac OS X Mavericks 10.9

Every time I open an `html` file I get this message in vim console:

```
Error detected while processing /Applications/MacVim.app/Contents/Resources/vim/runtime/syntax/html.vim:
line  208:
E409: Unknown group name: css.*Attr,css.*Prop,cssComment,cssLength,cssColor,cssURL,cssImportant,cssError,cssString,@htmlPreproc
E475: Invalid argument: htmlCssDefinition matchgroup=htmlArg start='style="' keepend matchgroup=htmlString end='"' contains=css.*Attr,css.*Prop,cssComment,cssLength,cssColor,cssU
RL,cssImportant,cssError,cssString,@htmlPreproc
```

I prefer this syntax plugin before all, thanks!

**Comment by lepture** [comment]
@dciccale I am using vim 7.3 now. I will try macvim 7.4 soon.

**Comment by lepture** [comment]
@dciccale I've tried macvim 7.4. It has no errors.

**Comment by dciccale** [comment]
I desabled my plugins one by one and each time opened an html file. When
activing this plugin that message is shown. What do you suggest?

**Comment by lepture** [comment]
@dciccale I see. It is your html syntax file that relies on a css syntax.

I am using another html syntax file, so I have no issue here.

**Comment by dciccale** [comment]
So you are using a plugin for html syntax? which one?

**Comment by lepture** [comment]
@dciccale I think it is https://github.com/lepture/vim-jinja/blob/master/syntax/html.vim

But I am not sure. This is absolute not the main syntax.

**Comment by dciccale** [comment]
Awesome I'll try it, so you say that using this one plus your plugin it
should be fine, right?

2013/12/11 Hsiaoming Yang notifications@github.com

**Comment by lepture** [comment]
@dciccale I am not sure. This one is not a main syntax file.

**Comment by dciccale** [comment]
I am not using any main syntax file for html, just using the native one.
Using the css3 syntax plugin "hail2u/vim-css3-syntax" on github, it doesn't
fails.

I will try the one you mentioned before and come back with an answer,
thanks man

2013/12/11 Hsiaoming Yang notifications@github.com

**Comment by dciccale** [comment]
Yes, that error message still appears when using the html syntax file you
told me plus your css3 plugin. Using the one I mentioned before, I have no
issues.

2013/12/11 Denis Ciccale dciccale@gmail.com

**Comment by lepture** [comment]
hail2u/vim-css3-syntax seems better than mine. Why not use it?

**Comment by dciccale** [comment]
In fact i am using that one now. Yours was cool but cor now i will stick
Keith the other. Thanks por the concern you can close this issue img you
want
